# Generated by Django 3.2.13 on 2022-08-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Pryority',
                'verbose_name_plural': 'Pryorities',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='pryority',
            field=models.ManyToManyField(blank=True, related_name='pryorities', to='tasks.Priority', verbose_name='Pryority'),
        ),
    ]
