# Generated by Django 3.2.13 on 2022-08-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220808_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='pryority',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ManyToManyField(blank=True, related_name='priorities', to='tasks.Priority', verbose_name='Priority'),
        ),
    ]
