# Generated by Django 3.2.13 on 2022-08-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220808_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], default=1, max_length=1, verbose_name='Prioridade'),
            preserve_default=False,
        ),
    ]
