# Generated by Django 3.2.12 on 2022-02-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220227_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cidade',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(choices=[('AM', 'AC - Acre'), ('AL', 'AL - Alagoas'), ('AP', 'AP - Amapá'), ('AM', 'AM - Amazonas'), ('BA', 'BA - Bahia'), ('CE', 'CE - Ceará'), ('DF', 'DF - Distrito Federal'), ('ES', 'ES - Espírito Santo'), ('GO', 'GO - Goiás'), ('MA', 'MA - Maranhão'), ('MG', 'MG - Minas Gerais'), ('MS', 'MS - Mato Grosso do Sul'), ('MT', 'MT - Mato Grosso'), ('PA', 'PA - Pará'), ('PB', 'PB - Paraíba'), ('PE', 'PE - Pernambuco'), ('PI', 'PI - Piauí'), ('PR', 'PR - Paraná'), ('RJ', 'RJ - Rio de Janeiro'), ('RN', 'RN - Rio Grande do Norte'), ('RO', 'RO - Rondônia'), ('RS', 'RS - Rio Grande do Sul'), ('RR', 'RR - Roraima'), ('SC', 'SC - Santa Catarina'), ('SE', 'SE - Sergipe'), ('SP', 'SP - São Paulo'), ('TO', 'TO - Tocantins')], default='BA', max_length=2, verbose_name='Estado'),
        ),
    ]
