def choices_estados():
    UF_CHOICES = (
        ("AM", "AC - Acre"),
        ("AL", "AL - Alagoas"),
        ("AP", "AP - Amapá"),
        ("AM", "AM - Amazonas"),
        ("BA", "BA - Bahia"),
        ("CE", "CE - Ceará"),
        ("DF", "DF - Distrito Federal"),
        ("ES", "ES - Espírito Santo"),
        ("GO", "GO - Goiás"),
        ("MA", "MA - Maranhão"),
        ("MG", "MG - Minas Gerais"),
        ("MS", "MS - Mato Grosso do Sul"),
        ("MT", "MT - Mato Grosso"),
        ("PA", "PA - Pará"),
        ("PB", "PB - Paraíba"),
        ("PE", "PE - Pernambuco"),
        ("PI", "PI - Piauí"),
        ("PR", "PR - Paraná"),
        ("RJ", "RJ - Rio de Janeiro"),
        ("RN", "RN - Rio Grande do Norte"),
        ("RO", "RO - Rondônia"),
        ("RS", "RS - Rio Grande do Sul"),
        ("RR", "RR - Roraima"),
        ("SC", "SC - Santa Catarina"),
        ("SE", "SE - Sergipe"),
        ("SP", "SP - São Paulo"),
        ("TO", "TO - Tocantins"),
    )
    return UF_CHOICES
